language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
matrix:
  allow_failures:
  - php: hhvm
mysql:
    - database: travis_ci_magento_module
    - username: root
    - encoding: utf8
env:
  - MAGENTO_VERSION=magento-ce-1.9.1.0
  - MAGENTO_VERSION=magento-ce-1.9.0.1
  - MAGENTO_VERSION=magento-ce-1.8.1.0
  - MAGENTO_VERSION=magento-ce-1.8.0.0
  - MAGENTO_VERSION=magento-ce-1.7.0.2
before_script:
  - mysql -e 'create database travis_ci_magento_module'